apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: FlyToday
  description: FlyToday Online Travel Agency
  links:
    - url: http://www.flytoday.ir/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: OTA
spec:
  type: organization
  profile:
    displayName: FlyToday
    email: info@flytoday.com
    picture: https://www.flytoday.ir/Content/Views/Global/images/Domains/40/FileNameLogoFile_637701587653270139_.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
    - ./team-c-group.yaml
    - ./team-d-group.yaml
